<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url; 
/**
 * Implements hook_form_alter().
 *
 * Will only load js/css files for node forms only
 */
function siteattention_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // To check that it is a node add/edit form $form['#attributes']['class'][1] == 'node-form'
  //dsm($form);

  $class_array = $form['#attributes']['class'];
  $space_separated = implode(" ", $class_array);
  if (preg_match('/node-form/',$space_separated)) {
    $form['#after_build'][] = 'siteattention_after_build';
  }
  
}


/**
 * Implements siteattention_after_build().
 *
 * Load js/css Files only for Node Form
 */
function siteattention_after_build($form, &$form_state) {
  //dsm($form);
  $account  = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  $username = $account->get('name')->value;
  $config   = \Drupal::config('siteattention.settings');
  $sa_key   = $config->get('siteattention.SA_KEY');
  $sa_iid   = $config->get('siteattention.SA_IID');
  $sa_iname = $config->get('siteattention.SA_INAME');
  
  /**** Get current page id and url ***/
  $node = $form_state->getFormObject()->getEntity();
  
  if(!empty($node)){
    $nid = ($node->id() != '') ? $node->id(): 0;
    $node_type = ($node->getType() != '') ? $node->getType(): '';
  }
  
  $options = ['absolute' => TRUE];
  $url = Url::fromRoute('entity.node.canonical', ['node' => $nid], $options)->toString();
  /**** Get current page id and url ***/

  $form['path_settings']['#open'] = TRUE;
  $form['#attached']['drupalSettings']['SA']['ContentType'] = $node_type;
  $form['#attached']['drupalSettings']['SA']['NodeID'] = $nid;
  $form['#attached']['drupalSettings']['SA']['pageUrl'] = $url;
  $form['#attached']['drupalSettings']['SA']['username'] = $username;
  $form['#attached']['drupalSettings']['SA']['KEY'] = $sa_key;
  $form['#attached']['drupalSettings']['SA']['IID'] = $sa_iid;
  $form['#attached']['drupalSettings']['SA']['INAME'] = $sa_iname;
  $form['#attached']['library'][] = "siteattention/siteattention.SiteAttentionDemoCMSModule.js";
  $form['#attached']['library'][] = "siteattention/siteattention.SiteAttentionModule.js";
  $form['#attached']['library'][] = "siteattention/siteattention.script.js";
  return $form;
}

/**
 * Implements hook_help().
 */
function siteattention_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.siteattention':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('SiteAttention provides support for Search Engine Optimization of your page content before it is being published.In this settings section you can configure how SiteAttention should interact with different properties of your site in Add/Edit mode.') . '</p>';
      $output .= '<h3>' . t('How SiteAttention Works') . '</h3>';
      $output .= '<dl>';
      $output .= '<dd>' . t('SiteAttention is a SEO tool that helps content writers optimize their content in real time using a sidebar overlay.The writer starts the process by selecting one or more keywords that the content should be optimized towards.') . '</dd>';
      $output .= '<dd>' . t('As soon as a keyword has been selected SiteAttention will calculate a page score based on a set of rules (shown below the keyword field). The rules are based on current SEO best practices and provide tips on how the writer can improve the content to be more SEO friendly.') . '</dd>';
      $output .= '<dd>' . t('Whenever the writer writes text in a content field the score is updated for each rule.') . '</dd>';
      $output .= '<dd>' . t('If properly optimized the score reaches 100% and a better search engine position can be achieved.') . '</dd>';
      $output .= '<dd>' . t('SiteAttention requires a license key to be used. This can either be a Freemium or Premium key:') . '</dd>';
      $output .= '<dd>' . t('If no key is provided SiteAttention will start up in a special “Register” mode, where it is possible to obtain a Freemium key by inputting contact information and registering for a key. Freemium keys can be upgraded to Premium at any later time.') . '</dd>';

      $output .= '</dl>';
      return $output;

    case 'siteattention.config':
      return '<p>' . t('SiteAttention provides support for Search Engine Optimization of your page content before it is being published.In this settings section you can configure how SiteAttention should interact with different properties of your site content in Add/Edit mode.') . '</p>';
  }
}
