<?php

/**
* Implements hook_node_presave
*/

function node_api_node_presave($node){
	//echo $node->nid.'<br />';
	//echo $node->uid.'<br />';
	//exit;
}

function node_api_node_update($node){
	/*dpm($node);
	$loaded_node = node_load($node->nid);
	dpm($loaded_node);*/
}

/**
* Implements hook_permission
*/

function node_api_permission(){
	return array(
		'node_api article unpublish articles' => array(
			'title' => t('Article Unpublish'),
		),
	);
}

/**
* Impelements hook_menu().
*/

function node_api_menu(){
	$items = array();

	$items['node/%node/article/unpublish'] = array(
    'title' => 'Unpublish',
    'access callback' => 'node_api_article_unpublish_access_check',
    'access arguments' => array(1),
    'page callback' => 'node_api_article_unpublish',
    'page arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_INLINE,
  );

  return $items;
}

function node_api_article_unpublish_access_check($node){echo 'ACCESS';exit;
	if ($node->type == 'article' && user_access('Article Unpublish')) {
    	return TRUE;
  	}

  	return FALSE;
}

/**
* Callback action to unpublish article.
*
* @param object $node Node object.
*/
function node_api_article_unpublish($node) {echo 'HAZRAT';exit;
  node_object_prepare($node);
  $node->status = 0;
  node_save($node);

  watchdog('node_api', __FUNCTION__ . ' -- Unpublished article "%title" (NID: %nid).', array('%title' => $node->title, '%nid' => $node->nid), WATCHDOG_NOTICE);

  $destination = drupal_get_destination();
  $destination = isset($destination['destination']) ? $destination['destination'] : '<front>';
  drupal_goto($destination);
}

