<?php
use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_views_query_alter().
 */
function timeslots_views_query_alter(\Drupal\views\ViewExecutable $view, \Drupal\views\Plugin\views\query\QueryPluginBase $query) {
  // make sure we're altering the correct view

    if ($view->storage->get('id') === 'timeslot_listing' && $view->current_display === 'timeslots_listing') {
        
        //$query->addWhere(0, 'timeslots.start_time', 1507298400, '>');
        $date = new DateTime();
        $date->setTimeZone(new DateTimeZone(drupal_get_user_timezone()));
        $current_time = $date->getTimestamp();
        $query->addWhere(0, 'timeslots.start_time', $current_time, '>');
        
    }
}

