<?php
/**
 * @file
 * Code for the Chad module.
 */
use Drupal\Core\Url;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RedirectResponse;
/**
 * Implements hook_entity_type_build().
 */
function bookingform_entity_type_build(array &$entity_types) {
  $entity_types['bookinginfo']->setFormClass('booking_display', '\Drupal\bookingform\Form\BookingForm');
}


function bookingform_theme($existing, $type, $theme, $path) {
    
  return [
    'thankyou_template' => [
       'variables' => array(),
    ],
    'gotopayment_template' => [
       'variables' => array(
           'session_info' => array(),
           'login_link' => '',
       )
    ],
    'timeperiod_template' => [
       'variables' => array(
           'time_periods' => array(),
           'tutor_img' => '',
           'session_length' => '',
           'timeslot_count' => '',
           'session_url' => '',
           'recess_time' => ''
       )
    ],
    'gotopayment_complete_template' => [
        'variables' => array(),
    ],
    'bookingresponse_template' => [
        'variables' => array(
            'action' => '',
            'template_header' => '',
            'tutor_from' => ''
        ),
    ],
    'bookingcancellation_template' => [
        'variables' => array(),
    ],
  ];
}

function bookingform_user_login($account) {
    
    $booking_url = "";
    $previousUrl = "";
    $previousUrl = \Drupal::request()->server->get('HTTP_REFERER');
    
    if($previousUrl != ''){
        $previous_url_arr = explode('/',$previousUrl);
        
        if($previous_url_arr[3] == 'node' || $previous_url_arr[4] == 'node'){
            if($previous_url_arr[3] == 'node'){
                $redirect_url = '/'.$previous_url_arr[3];
                $redirect_url .= '/'.$previous_url_arr[4];
            }else{
                $redirect_url = '/'.$previous_url_arr[4];
                $redirect_url .= '/'.$previous_url_arr[5];
            }
        }
        
        // Redirect to the same goto payment page after login
        if($previous_url_arr[3] == 'booking'){
            $gotopayment_path_arr = explode('?',$previous_url_arr[4]);
            if($gotopayment_path_arr[0] == "gotopayment"){
                $redirect_url = '/'.$previous_url_arr[3].'/'.$previous_url_arr[4];
            }
        }
        
        $url = Url::fromUserInput($redirect_url);
        $response = new RedirectResponse($url->setAbsolute()->toString());
        $response->send();
    }
        
}

/*
 * @file
 * code for resume module
*/

function bookingform_mail($key, &$message, $params) {
    
    switch ($key) {
        case 'booking_request':
            $message['from'] = 'larskoeie@gmail.com';
            $message['subject'] = $params['subject']; //"Booking Request";
            $message['body'][] = $params['body'];
        break;
    
        case 'booking_response':
            $message['from'] = 'larskoeie@gmail.com';
            $message['subject'] = $params['subject']; //"Booking Response";
            $message['body'][] = $params['body'];
        break;

        
    }
}

function bookingform_mail_alter(&$message) {
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
    switch ($message['key']) {
        case 'booking_request':
            
        break;
    }
}


