<?php
/**
* @file
*
* Create scheema for mymodule
*
* @author Saru1683
*/

/**
* Implemenation of hook_schema
*
* @author Saru1683
*/
function mymodule_schema() {
$schema['wc_count_trial_version_download'] = array(
'fields' => array(
'download_id' => array(
'type' => 'serial',
'lenght' => 11,
),

'uid' => array(
'type' => 'int',
'lenght' => 11,
),

'date' => array(
'type' => 'int',
'lenght' => 11,
),
),
'primary key' => array('download_id'),
);

return $schema;
}
