<?php

function entitydemo_menu(){
    $items['project/%'] = array(
        'title' => 'Project',
        'page callback' => 'demo_view_project',
        'page arguments' => array(1),
        'access arguments' => array('access content'),
    );
    
    return $items;
}

function demo_view_project($id){
    //$projects = entity_load('project', array($id));
    //return print_r($projects);
    //$project = $projects[$id];
    
    //drupal_set_title($project->name);
    //$output = entity_view('project', array($project));
    $output = 'HAZRAT ALi';
    
    return $output;
}
/**
 * Implements hook_entity_info().
 */
function entitydemo_info(){
    $info = array();
    
    $info['project'] = array(
      'label' => t('Project'),
        'base table' => 'demo_projects',
        'entity keys' => array(
            'id' => 'id',
            'label' => 'name',
        ),
        'module' => 'demo',
    );
    
    return $info;
}