<?php
/*
 * @file
 * code for testhtmlmail module
*/

function testhtmlmail_mail($key, &$message, $params) {
  
  	if (($key == 'booking_request') ) { // || ($key == 'notify_expert')
    	$message['from'] = 'larskoeie@gmail.com';
    	$message['subject'] = "Test Mail From PTM";
    	$message['body'][] = $params['body'];
  	}
}

function testhtmlmail_mail_alter(&$message) {
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
    switch ($message['key']) {
        case 'booking_request':
            
        break;
    }
}



/*
$body =
"Hi,

I'm just showing off my work ...
Works nicely huh?
Should probably add a password here somewhere?

Your username: " . $params['email'] . "
Your password: " . $params['password'] . "

See ya!";

  $message['subject'] = "EuRA account registration";
  $message['body'][] = Drupal\Core\Mail\MailFormatHelper::htmlToText($body);
*/
?>
